// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto_BackEnd_Final.Data;

#nullable disable

namespace Projeto_BackEnd_Final.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260626005012_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Projeto_BackEnd_Final.Models.Responsavel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("TipoResponsavel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TB_RESPONSAVEL", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cpf = "",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Endereco = "",
                            Nome = "",
                            TipoResponsavel = 0
                        },
                        new
                        {
                            Id = 2,
                            Cpf = "",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Endereco = "",
                            Nome = "",
                            TipoResponsavel = 0
                        },
                        new
                        {
                            Id = 3,
                            Cpf = "",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Endereco = "",
                            Nome = "",
                            TipoResponsavel = 0
                        },
                        new
                        {
                            Id = 4,
                            Cpf = "",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Endereco = "",
                            Nome = "",
                            TipoResponsavel = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
